name: Build and Deploy # 为GitHub Actions工作流命名

on:
  push:
    branches:
      - master # 当推送到main分支时触发工作流

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest # 使用Ubuntu操作系统作为运行环境

    steps:
      - name: Checkout # 步骤1：从仓库检出代码
        uses: actions/checkout@v3
        with:
          persist-credentials: false # 不保留凭据

      - name: Build and Deploy # 步骤2：构建和部署
        uses: appleboy/ssh-action@master # 使用SSH Action插件
        with:
          host: ${{ secrets.SERVER_HOST }} # 从GitHub Secrets中获取服务器主机名
          username: ${{ secrets.SERVER_USERNAME }} # 从GitHub Secrets中获取服务器用户名
          password: ${{ secrets.SERVER_PASSWORD }} # 从GitHub Secrets中获取服务器密码
          port: ${{ secrets.SERVER_PORT }} # 从GitHub Secrets中获取服务器端口号
          script: |
            cd /var/www/my_blog  # 切换到项目目录
            git pull  # 从远程仓库拉取最新代码
            npm install --legacy-peer-deps  # 安装项目依赖
            npm run build  # 执行构建脚本
            pm2 restart my_blog --interpreter none -- start  # 使用PM2重启应用程序

